controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app_weather:
    path: /weather/weather
    controller: App\Controller\WeatherController::weather

app_twitter:
    path: /twitter/twitter
    controller: App\Controller\TwitterController::twitter

app_homepage:
    path: /twitter/twitter
    controller: App\Controller\TwitterController::twitter
